services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: video-summarizer-server
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: video-summarizer-client
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    name: video-summarizer-net